version: '3.8'

services:
  postgres_db:
    # ... (dados existentes)
    image: postgres:16-alpine
    container_name: meu_postgres_dev
    environment:
      # ... (suas variáveis)
      POSTGRES_DB: Carteira-Digital-db
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

    # 🚨 NOVO: HEALTHCHECK para garantir que o DB está pronto
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"] # Testa a conexão usando o usuário 'root'
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s # Espera 10s antes de começar a checar 
  # -------------------------------------------------------------------
  # NOVO SERVIÇO: SUA APLICAÇÃO NESTJS
  # -------------------------------------------------------------------
  app:
    # 1. Diz ao Docker Compose para CONSTRUIR a imagem
    #    usando o Dockerfile que está no diretório atual.
    build: 
      context: . 
      dockerfile: Dockerfile

    # 2. Define um nome fixo
    container_name: carteira_digital_app

    # 3. Mapeamento de Portas: expõe a porta 3000 do contêiner para a 8080 da sua máquina local.
    ports:
      - "8080:3000" 

    # 4. Variáveis de Ambiente
    environment:
      # O HOSTNAME DEVE SER O NOME DO SERVIÇO: 'postgres_db'
      # Isso garante que sua aplicação consiga se conectar ao banco de dados.
      # AJUSTE: Você pode precisar de variáveis adicionais como POSTGRES_USER e POSTGRES_PASSWORD
      DATABASE_URL: postgres://root:root@postgres_db:5432/Carteira-Digital-db
      # Você pode adicionar mais variáveis do seu arquivo .env aqui, por exemplo:
      # JWT_SECRET: ${JWT_SECRET} 
      
    # 5. Dependências: Garante que o DB inicie antes da aplicação.
    # O 'service_healthy' é bom se você configurar o HEALTHCHECK no DB,
    # mas 'service_started' geralmente é suficiente para o NestJS.
    depends_on:
      postgres_db:
        condition: service_healthy 

    # 6. Reinício:
    restart: unless-stopped

    command: sh -c "npx prisma migrate deploy && npm run start:prod"

# Define os volumes que o Docker deve gerenciar (para persistência de dados).
volumes:
  postgres_data: